import { Inter } from "next/font/google";

import TanstackProvider from "@/provider/TanstackProvider";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <TanstackProvider>{children}</TanstackProvider>
            </body>
        </html>
    );
}
